### ISSUE TITLE
有没有使用demo？

### ISSUE THREAD

**Issue by callmesoul** [a597873885/webfunny_monitor#1]
文档太多简单了，可有使用案例？

**Comment by a597873885** [comment]
https://www.cnblogs.com/warm-stranger/p/9417084.html

**Comment by lijicheng123** [comment]
localhost的一定要重定向https吗

**Comment by a597873885** [comment]
@lijicheng123 你是指？   探针里边并没有这样的逻辑啊。

**Comment by lijicheng123** [comment]
@a597873885 

![image](https://user-images.githubusercontent.com/15669871/56564995-deb59580-65e1-11e9-9419-a8ac815ef720.png)
这样自动重定向

**Comment by callmesoul** [comment]
作者的项目挺好的，可惜是react技术栈。
我自己写了个vue的前端错误监控系统，实现了基本的错误拦击和邮件报错功能。
后续有空会扩展功能。
可以了解下。
@lijicheng123 
https://github.com/callmesoul/frontend-sniper

**Comment by a597873885** [comment]
@lijicheng123 你这个表现确实有点奇怪， 代码里边并没有做任何重定向的操作， 你试着检查一下Nginx的配置，或者贴出来我看一下

**Comment by lijicheng123** [comment]
> @lijicheng123 你这个表现确实有点奇怪， 代码里边并没有做任何重定向的操作， 你试着检查一下Nginx的配置，或者贴出来我看一下

还没放到nginx，只是在开发环境就一堆问题，能否出一个好一点的文档呢

**Comment by lijicheng123** [comment]
> 作者的项目挺好的，可惜是react技术栈。
> 我自己写了个vue的前端错误监控系统，实现了基本的错误拦击和邮件报错功能。
> 后续有空会扩展功能。
> 可以了解下。
> @lijicheng123
> https://github.com/callmesoul/frontend-sniper

你这个靠谱不

**Comment by a597873885** [comment]
@lijicheng123 嗯，目前文档确实太少，我把接口监控写完了之后，会着重把文档补一下。 因为是业余时间开发，迭代比较慢，哈哈。

**Comment by callmesoul** [comment]
> > 作者的项目挺好的，可惜是react技术栈。
> > 我自己写了个vue的前端错误监控系统，实现了基本的错误拦击和邮件报错功能。
> > 后续有空会扩展功能。
> > 可以了解下。
> > @lijicheng123
> > https://github.com/callmesoul/frontend-sniper
> 
> 你这个靠谱不

看你什么需求咯，
可以上线，
可以收集错误，
可以邮件通知错误，
基本功能咯

**Comment by lijicheng123** [comment]
> > > 作者的项目挺好的，可惜是react技术栈。
> > > 我自己写了个vue的前端错误监控系统，实现了基本的错误拦击和邮件报错功能。
> > > 后续有空会扩展功能。
> > > 可以了解下。
> > > @lijicheng123
> > > https://github.com/callmesoul/frontend-sniper
> > 
> > 
> > 你这个靠谱不
> 
> 看你什么需求咯，
> 可以上线，
> 可以收集错误，
> 可以邮件通知错误，
> 基本功能咯

看了你的demo好多地方还是不能点么

**Comment by callmesoul** [comment]
@lijicheng123 初始项目，有些按钮没完善，但基本功能已完成，不影响使用，后面会慢慢完善，也欢迎加入
