### ISSUE TITLE
请问能检测到 grpc-web 的接口请求吗？

### ISSUE THREAD

**Issue by kybetter** [a597873885/webfunny_monitor#104]
如题，grpc-web 是使用 google 的那一套东西，从控制台中来看，不管是请求参数还是响应的结果都是由一些二进制格式的数据转成的字符串（完全看不出来是什么内容）。

所以，对于使用了 grpc-web 的项目，你们能够监控到吗？

**Comment by a597873885** [comment]
目前可能不行，没有专门对其处理过



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liang Zhao <notifications@github.com&gt;
发送时间: 2020年10月30日 16:29
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 请问能检测到 grpc-web 的接口请求吗？ (#104)
