### ISSUE TITLE
部署成功，浏览器访问报错，Target container is not a DOM element.

### ISSUE THREAD

**Issue by Hooho** [a597873885/webfunny_monitor#112]
浏览器一直报了好多这个错，而且只有报这个错，项目的日志没有错误信息
![image](https://user-images.githubusercontent.com/18716647/99561324-cb5aee00-2a01-11eb-8021-09a30a50f55b.png)

**Comment by a597873885** [comment]
@Hooho  这个应该是访问路径不对  /webfunny/home.html

**Comment by Hooho** [comment]
直接访问 /webfunny/ 导致的
