### ISSUE TITLE
服务端报错，某些表不存在

### ISSUE THREAD

**Issue by Hooho** [a597873885/webfunny_monitor#113]
大概报了这三个表不存在

Table 'webfunny_db.webfunny621CustomerPV20201119' doesn't exist
Table 'webfunny_db.webfunny621JavascriptErrorInfo20201119' doesn't exist
Table 'webfunny_db.webfunny621CustomerPV20201119' doesn't exist

**Comment by a597873885** [comment]
@Hooho  这个问题应该建表的过程中，遇到的分析事件，可以忽略。
