### ISSUE TITLE
部署最新版本首页js报错

### ISSUE THREAD

**Issue by zenonux** [a597873885/webfunny_monitor#119]
`Uncaught (in promise) TypeError: Cannot read property 'userTag' of undefined`

**Comment by a597873885** [comment]
@zenonux  应该是老项目的探针吧，在项目详情页面，点击一下更新探针，然后重新部署探针代码

**Comment by zenonux** [comment]
> @zenonux 应该是老项目的探针吧，在项目详情页面，点击一下更新探针，然后重新部署探针代码

 我是首次部署这个项目，不过更新探针之后确实不报错，不过在详情页有别的错误，不清楚是不是新引入的。
![image](https://user-images.githubusercontent.com/8474239/100068620-bb646380-2e72-11eb-8c9a-1a93e77e9996.png)

**Comment by a597873885** [comment]
@zenonux webfunny的报错，你可以暂时不用关注

**Comment by a597873885** [comment]
只要不影响你使用就行
