### ISSUE TITLE
nginx配置太复杂了

### ISSUE THREAD

**Issue by zenonux** [a597873885/webfunny_monitor#120]
看文档nginx的配置好复杂，看不懂。目前代码里使用ip方式部署。nginx 转发`  location /
        {
                    proxy_pass http://127.0.0.1:8010;
        }
        location /server{
                    proxy_pass http://127.0.0.1:8011;
        }
        location /socket{
                    proxy_pass http://127.0.0.1:8011;
        }`，然后再把探针里面的ip加端口号改为nginx配置的域名，测试也能获取到上报的错误，不知道这样改可行不？对nginx不熟

**Comment by a597873885** [comment]
@zenonux  nginx的配置需要具备一定量的运维知识，建议先使用ip进行部署，等到需要配置域名的时候，在找运维小伙伴帮忙配置nginx代理
