### ISSUE TITLE
单页面应用怎么捕获不到页面name

### ISSUE THREAD

**Issue by LoveNemoLau** [a597873885/webfunny_monitor#127]

**Comment by a597873885** [comment]
@LoveNemoLau  不是很明白你的意思，可以描述清楚一点吗，你是指url? title?

**Comment by LoveNemoLau** [comment]
> @LoveNemoLau 不是很明白你的意思，可以描述清楚一点吗，你是指url? title?

如何在h5app中能捕获到单页应用的路由。
![image](https://user-images.githubusercontent.com/34276605/101236706-53cdd400-370e-11eb-9391-870e1d0f5706.png)

**Comment by a597873885** [comment]
@LoveNemoLau  这个确实有点奇怪，怎么会捕捉不到完整的url呢，你用的是react、vue还是？ 我稍后看下原因。

**Comment by LoveNemoLau** [comment]
> @LoveNemoLau 这个确实有点奇怪，怎么会捕捉不到完整的url呢，你用的是react、vue还是？ 我稍后看下原因。

你的捕获是没问题，只是我们的应用是在一个页面里进行的切换，每个页面都存入history中所有页面的前进后退都是操作history实现的。想要在每个页面created的时候能不能给探针传个参数，记录到我进入那个页面了

**Comment by a597873885** [comment]
@LoveNemoLau  嗯，这个问题我们已经发现了，我们将会增加对history变化的监控，这样你的页面变化就能够统计出来了。

**Comment by LoveNemoLau** [comment]
> @LoveNemoLau 嗯，这个问题我们已经发现了，我们将会增加对history变化的监控，这样你的页面变化就能够统计出来了。
谢谢！
