### ISSUE TITLE
点击JS错误统计报错

### ISSUE THREAD

**Issue by huangying10000** [a597873885/webfunny_monitor#136]
点击JS错误统计   自定义异常统计详情报错

![1608601157208_F8B09E64-44DB-4423-8E71-0C85345A75C4](https://user-images.githubusercontent.com/44154448/102838728-df976e00-4439-11eb-997d-966be5e377c0.png)
![1608601082380_B95968B9-F3EA-4CD2-9BE3-CAF0907DBEBE](https://user-images.githubusercontent.com/44154448/102838736-e1613180-4439-11eb-92f2-f2d45808ec2d.png)

**Comment by a597873885** [comment]
@huangying10000  你好，从错误信息来看，多半是react用法不规范导致的警告，没有错误堆栈，点击进去才会报错。 这种错误一般也无需分析，这种错误webfunny无法分析，我稍后会对这种情况做处理。
