### ISSUE TITLE
探针限制了权限吗？

### ISSUE THREAD

**Issue by mesuzhiben** [a597873885/webfunny_monitor#14]
探针创建需要注册，注册登陆的接口都是404的
![image](https://user-images.githubusercontent.com/9128769/67192413-2187e700-f426-11e9-96e4-d4dafdaadb4e.png)

**Comment by a597873885** [comment]
@mesuzhiben 部署版是不需要注册的，我更新了代码，修复了这个bug。  拉取新代码之后， 执行 node config.js   重新配置运行，就可以了
