### ISSUE TITLE
查看应用详情问题

### ISSUE THREAD

**Issue by taoqiyang** [a597873885/webfunny_monitor#145]
![image](https://user-images.githubusercontent.com/5866448/104403651-f1c97f80-5593-11eb-8c72-4117929b4777.png)
如图，每次从首页点击某个应用的应用设置或者预览进入设置页面或详情页面时，接口请求所带的webMonitorId都是undefined,导致不管点击哪个应用进去看到的都是首页的第一个。

**Comment by a597873885** [comment]
@taoqiyang  这个问题已经修复了，请问是2.2.2版本号吗？

**Comment by taoqiyang** [comment]
在哪儿看版本号呢
