### ISSUE TITLE
用户分析-无USERID查询

### ISSUE THREAD

**Issue by mesuzhiben** [a597873885/webfunny_monitor#15]
您好问下：用户分析-无USERID查询-列表为什么会原本有数据 过一分钟刷新之后就变成没数据？
![image](https://user-images.githubusercontent.com/9128769/67202381-14c1be00-f43b-11e9-857f-c3cedb9f6a11.png)
![image](https://user-images.githubusercontent.com/9128769/67202392-1c816280-f43b-11e9-883a-884fdff75220.png)

**Comment by a597873885** [comment]
好像是默认查询最近几分钟的数据，因为我这边数据量比较大，查询比较耗资源，所以默认时间很短

**Comment by mesuzhiben** [comment]
![image](https://user-images.githubusercontent.com/9128769/67254736-42494e80-f4b1-11e9-81c0-de36faf23a92.png)
这个列表ip查询
![image](https://user-images.githubusercontent.com/9128769/67254752-5bea9600-f4b1-11e9-81ca-8ff69ba621f5.png)
输入192.168.218.228 IP查不出东西 这个查询ip的格式规范是啥

**Comment by a597873885** [comment]
因为你的是本地地址，都有前缀，所以查不出来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mesuzhiben <notifications@github.com&gt;
发送时间: 2019年10月22日 09:55
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 用户分析-无USERID查询 (#15)





 这个列表ip查询
 
 输入192.168.218.228 IP查不出东西 这个查询ip的格式规范是啥

**Comment by mesuzhiben** [comment]
一定需要域名吗？

**Comment by a597873885** [comment]
你是指？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mesuzhiben <notifications@github.com&gt;
发送时间: 2019年10月22日 10:01
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 用户分析-无USERID查询 (#15)




一定需要域名吗？

**Comment by mesuzhiben** [comment]
![image](https://user-images.githubusercontent.com/9128769/67255125-15963680-f4b3-11e9-9f39-4fc00bbca978.png)
![image](https://user-images.githubusercontent.com/9128769/67255128-18912700-f4b3-11e9-8884-9d0697d857b5.png)
点击查看详情会报错 匹配的url会出错

**Comment by a597873885** [comment]
抱歉，这可能又是一个bug，我稍后修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mesuzhiben <notifications@github.com&gt;
发送时间: 2019年10月22日 10:03
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 用户分析-无USERID查询 (#15)





 
 点击查看详情会报错 匹配的url会出错

**Comment by a597873885** [comment]
这个功能是来辅助userid查询方式的，我没有写得太细致，用起来可能不太顺手，哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mesuzhiben <notifications@github.com&gt;
发送时间: 2019年10月22日 09:55
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 用户分析-无USERID查询 (#15)





 这个列表ip查询
 
 输入192.168.218.228 IP查不出东西 这个查询ip的格式规范是啥

**Comment by mesuzhiben** [comment]
理解！您好 查询这快 能少个限制吗 比如 IP和时间不是共同必选的 我只要查时间范围就好了！IP不必填！因为列表几分钟就会消失 历史的我就查看不到了

**Comment by a597873885** [comment]
嗯，好，等下更新告诉你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mesuzhiben <notifications@github.com&gt;
发送时间: 2019年10月22日 10:08
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 用户分析-无USERID查询 (#15)




理解！您好 查询这快 能少个限制吗 比如 IP和时间不是共同必选的 我只要查时间范围就好了！IP不必填！因为列表几分钟就会消失 历史的我就查看不到了

**Comment by mesuzhiben** [comment]
好的谢谢

**Comment by a597873885** [comment]
你好，查询的优化已经做了，至于这个uri的报错，我还没定位到原因，可能是你的地址比较特殊，因为我这边是OK的，是可以使用localhost试试。 更新后还是要使用node config进行配置

**Comment by mesuzhiben** [comment]
http://localhost:8011/server/upLog 404 (Not Found)

**Comment by a597873885** [comment]
看下配置文件是否被覆盖了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mesuzhiben <notifications@github.com&gt;
发送时间: 2019年10月22日 11:58
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 用户分析-无USERID查询 (#15)




http://localhost:8011/server/upLog 404 (Not Found)

**Comment by mesuzhiben** [comment]
是哪个配置文件？您最新的这个版本好像就出问题了 uplog这个接口是404了

**Comment by mesuzhiben** [comment]
![image](https://user-images.githubusercontent.com/9128769/67260370-821e2f00-f4cd-11e9-8abb-3d27aca91d87.png)
您好这是上报接口404的报错log

![image](https://user-images.githubusercontent.com/9128769/67260390-9a8e4980-f4cd-11e9-8be0-8f468693167c.png)
这是另一个接口的报错log

**Comment by a597873885** [comment]
@mesuzhiben 你好，七天留存率的bug修复了，日志上传404的问题我还不能够准确定位，因为我这边测试，都没有任何问题。  你这个问题是偶尔出现，还是一直出现

**Comment by mesuzhiben** [comment]
我clone了你的项目 重新部署了 就一直这样了 我是本地的 用的是本地IP地址 不是localhost 目前是一直都这样 您说的配置文件是根目录的config.js吗？配置如下
![image](https://user-images.githubusercontent.com/9128769/67261181-21452580-f4d2-11e9-9141-9b8ad534a3f3.png)

**Comment by a597873885** [comment]
@mesuzhiben  这样吧，你在我的网站上新建一个应用ID，部署到你本地的项目上，我看看上报日志会不会有报错。

**Comment by mesuzhiben** [comment]
您看下，生成了
项目名称：daxing
![image](https://user-images.githubusercontent.com/9128769/67263927-24ddaa00-f4dc-11e9-93cd-003cf5306495.png)

**Comment by a597873885** [comment]
哈哈，可能是我没有描述清楚， 上报域名填写 www.webfunny.cn  才能上报到我的服务器上，我才能够观察到你的日志

**Comment by mesuzhiben** [comment]
你库里看下 我填的是这个域名生成的探针！ 然后我页面请求就是localhost 是不是探针有点出入？

**Comment by a597873885** [comment]
你的url是使用localhost吗？ 为了防止上报太多本地信息，localhost的域名只上报到localhost的服务上

**Comment by mesuzhiben** [comment]
我换成ip访问了，您看下 404

**Comment by a597873885** [comment]
@mesuzhiben 我看你的日志都过来了，不知道为啥还是404，没有看到特别明显的错误日志，不确定是不是你的

**Comment by mesuzhiben** [comment]
时好时坏 ，我看了下，现在又200了
![image](https://user-images.githubusercontent.com/9128769/67270061-72f9aa00-f4ea-11e9-9356-8fc0e6bcdfc2.png)
z这个查看详情能看下吗？
![image](https://user-images.githubusercontent.com/9128769/67270120-90c70f00-f4ea-11e9-8627-95ade1be3a6b.png)

就卡着这里了

**Comment by a597873885** [comment]
这个问题是你的url命中了我的加密规则了，导致url解析不出来了，😂

**Comment by mesuzhiben** [comment]
有什么要求吗 我是正常的测试环境的地址 也就是本地IP

**Comment by a597873885** [comment]
拉去一下最新代码吧，还是要执行以下node config 。 如果解析不出来的url，我就不解析了。

**Comment by a597873885** [comment]
404的问题应该不大，你暂时先这么用着吧，等我具体处理以后，页面上也会有通知的。
