### ISSUE TITLE
是否能支持taro 第三方小程序开发框架 

### ISSUE THREAD

**Issue by allen-wiki** [a597873885/webfunny_monitor#158]
是否能放出未压缩的探针代码 方便我们自己接入其他平台的小程序框架

**Comment by a597873885** [comment]
@allen-wIki  你好，我们暂时还不能够支持， 小程序探针我们是开放出来的， 如果你有兴趣，可以帮助我们完善一下，我们会尽快支持，感谢。

**Comment by GideonSenku** [comment]
简单看了一下，没有实现页面级别的性能监控啊

**Comment by allen-wiki** [comment]
> 简单看一下，没有等级的性能监控啊

?????

**Comment by a597873885** [comment]
@GideonSenku 暂时没有哈，我们年后会准备支持页面性能分析
