### ISSUE TITLE
没法运行起来

### ISSUE THREAD

**Issue by alanpeng2019** [a597873885/webfunny_monitor#16]
环境
WIN10
E:\webfunny_monitor-master>node -v
v10.16.3

E:\webfunny_monitor-master>npm -v
6.12.0
 
1 npm run test_start 报错
E:\webfunny_monitor-master>npm run test_start
npm ERR! missing script: test_start
npm ERR!
npm ERR! Did you mean this?
npm ERR!     start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-10-22T10_25_47_446Z-debug.log

 
 2 config/db.js  修改好了
 
 3 node config.js  可以通过
 
 4 npm run table_config  可以生成库表
 
 5 npm run start 报错
E:\webfunny_monitor-master>npm run start

> webfunny-servers@1.0.0 start E:\webfunny_monitor-master
> bin/www

'bin' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webfunny-servers@1.0.0 start: `bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webfunny-servers@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-10-22T10_00_45_498Z-debug.log

麻烦看看是什么原因

提个建议，有个稳定的版本？

**Comment by a597873885** [comment]
你的package.json 文件里边有这个命令吗？

![image](https://user-images.githubusercontent.com/26519165/67289596-6f2d4e00-f511-11e9-8018-7218113b8107.png)

**Comment by alanpeng2019** [comment]
多谢回复。明天我看一下有没有test_start。

test_start可以不跑，第五点可能什么原因。

**Comment by a597873885** [comment]
@alanpeng2019  bin/www 这个文件是有的吧？ 
也许是windows系统跟其他系统识别机制不一样，我把start命令改动了一下，你拉取新代码试一下

**Comment by dragonnahs** [comment]
"start": "./bin/www.js", 这里少些了，前面加上node或者nodemon就可以了，"start": "nodemon ./bin/www.js",

**Comment by a597873885** [comment]
也许windows系统确实需要加这个

**Comment by dragonnahs** [comment]
"start": "./bin/www", 这里少些了，前面加上node或者nodemon就可以了，"start": "nodemon ./bin/www",

**Comment by alanpeng2019** [comment]
"start": "./bin/www"  改为  "start": "node /bin/www"

前面加上 node 可以了。在看里面的详细功能了。

**Comment by alanpeng2019** [comment]
跑起来后，创建应用没法保存，提示404createproject不存在，看controll压缩了
这个本地能部署运行?怎么配，还少了什么?

**Comment by a597873885** [comment]
@alanpeng2019 看下logs/目录下日志怎么报错的

**Comment by alanpeng2019** [comment]
![Uploading 图片.png…]()

DEV启动

root@ubuntu:~/webfunny_monitor-master# npm run dev

> webfunny-servers@1.0.0 dev /home/alanpeng/webfunny_monitor-master
> nodemon bin/www

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node bin/www`

info/error 情况
root@ubuntu:~/webfunny_monitor-master/logs# tail -f errors/error-2019-10-23.log 

root@ubuntu:~/webfunny_monitor-master/logs# tail -f info/info-2019-10-23.log    
[2019-10-23T11:05:53.345] [INFO] responseLog - msg: ReferenceError: fs is not defined

[2019-10-23T12:04:53.350] [INFO] responseLog - msg: ReferenceError: fs is not defined

[2019-10-23T13:03:53.355] [INFO] responseLog - msg: ReferenceError: fs is not defined

[2019-10-23T14:02:53.356] [INFO] responseLog - msg: ReferenceError: fs is not defined

[2019-10-23T15:01:53.358] [INFO] responseLog - msg: ReferenceError: fs is not defined

**Comment by a597873885** [comment]
需要安装一下 fs模块

**Comment by alanpeng2019** [comment]
搞定了，可以用了
