### ISSUE TITLE
2.2.9 版本 用户行为查询 ，更改时间报错

### ISSUE THREAD

**Issue by DevilLeven** [a597873885/webfunny_monitor#162]
![image](https://user-images.githubusercontent.com/21081386/112077785-253e1100-8bb8-11eb-9f28-b8f6eff4008f.png)

**Comment by a597873885** [comment]
@DevilLeven  你好，我们也收到这个问题的反馈了，我们将会在下周一修复此问题。

**Comment by a597873885** [comment]
问题已修复
