### ISSUE TITLE
最新提交的代码有问题, 一直重定向

### ISSUE THREAD

**Issue by dengshenkk** [a597873885/webfunny_monitor#164]
这次提交有影响 648123e019777c0bf7c92a6e68f708cb461ed915
回退到这里解决 9adf281f262f0710e9f882e765082132530330b6

**Comment by a597873885** [comment]
@dengshenkk 请问在哪个页面重定向的？

**Comment by 13160692449** [comment]
安装完后登录界面一直重定向
![image](https://user-images.githubusercontent.com/48813566/112805568-5468ec80-90a8-11eb-8d22-ebfff58cc8e8.png)

**Comment by a597873885** [comment]
你好，我知道原因了，明天修复一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: caix ***@***.***&gt;
发送时间: 2021年3月29日 16:04
收件人: a597873885/webfunny_monitor ***@***.***&gt;
抄送: Webfunny 前端监控 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[a597873885/webfunny_monitor] 最新提交的代码有问题, 一直重定向 (#164)





 
安装完后登录界面一直重定向

**Comment by a597873885** [comment]
@dengshenkk @13160692449  已修复了，请更新一下代码即可。

**Comment by 13160692449** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Webfunny ***@***.***&gt;; 
发送时间: 2021年3月29日(星期一) 晚上10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [a597873885/webfunny_monitor] 最新提交的代码有问题, 一直重定向 (#164)





 
@dengshenkk @13160692449  已修复了，请更新一下代码即可。

**Comment by dengshenkk** [comment]
closed

**Comment by dengshenkk** [comment]
done
