### ISSUE TITLE
[BUG] 每天晚上重启生成以后创建表的进程死掉.message: Table 'webfunny_db.webfunnyxxxx202xxxxx' doesn't exist

### ISSUE THREAD

**Issue by zh417233956** [a597873885/webfunny_monitor#176]
1.新的站点创建以后，发现没有生成表，然后查看进程连续好几天的重启脚本都死掉了，导致过load average过高；
2.执行npm run table_config，一直停滞， 日志提示：msg: 命令配置完成, 请执行命令: npm run table_create
![image](https://user-images.githubusercontent.com/22386206/117915718-73e66c80-b318-11eb-9876-393ad69108c8.png)
![image](https://user-images.githubusercontent.com/22386206/117915741-7e086b00-b318-11eb-9e8f-243d125caa7c.png)
![image](https://user-images.githubusercontent.com/22386206/117915750-82cd1f00-b318-11eb-9df5-f213fb0182d1.png)
![image](https://user-images.githubusercontent.com/22386206/117915758-852f7900-b318-11eb-860d-f12b2ed02089.png)

**Comment by a597873885** [comment]
@zh417233956  你这个表现确实很奇怪，重启脚本和创建命令的脚本似乎都无法正常进行。

**Comment by a597873885** [comment]
能否这样做试下： 1. 手动杀掉webfunny相关的进程，2. 执行 npm run prd 启动程序， 3. 执行 npm run table_config 修复今天的表

**Comment by zh417233956** [comment]
在config/db_local.js中为了解决数据库的相关问题，pool.min 为0会自动释放连接，大于0 则不会自动释放，需要主动close，因此我们修改了pool.min=10，由此引发异常；现已经改回0，但是数据库连接数一直报高，，已关闭日志上报，准备接入rabbitmq
