### ISSUE TITLE
探针访问https://pv.sohu.com/cityjson?ie=utf-8 cors问题

### ISSUE THREAD

**Issue by huangang** [a597873885/webfunny_monitor#177]
Access to fetch at 'https://pv.sohu.com/cityjson?ie=utf-8' from origin 'https://xxx.xxx.com has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by a597873885** [comment]
@huangang  你好， 这个是为了让位置信息更加全面，加了本地查询的操作，如果出现失败，失败一次就不会再发了。对项目没有任何影响，请放心。
