### ISSUE TITLE
没有成功部署，打开页面报错

### ISSUE THREAD

**Issue by AloneFire** [a597873885/webfunny_monitor#18]
您好，clone 项目后 ，执行  `npm run test_start` ，打开页面报错并没有看到数据 ， 运行环境是 linux ，请问是什么原因

![76933F73-FEBF-4d2d-9965-129AD1823E9C](https://user-images.githubusercontent.com/20330223/67735143-37a53100-fa3e-11e9-828e-c8a4b86e4d49.png)

**Comment by a597873885** [comment]
你的配置文件写错了
