### ISSUE TITLE
无法初始化admin权限，邮件无法发送

### ISSUE THREAD

**Issue by Nginx1** [a597873885/webfunny_monitor#192]
无法初始化admin权限，信息填写完成后点击开启前端监控会卡住
报错如下
![1629133912(1)](https://user-images.githubusercontent.com/40064027/129603570-0cf2b188-6819-425d-85a7-2cd8d6aab5ac.png)
![1629133944(1)](https://user-images.githubusercontent.com/40064027/129603571-0c2acb09-4333-47cf-9893-f731afc7f7ea.png)
邮件无法发送报错如下
![1629134407(1)](https://user-images.githubusercontent.com/40064027/129603842-bb6f2071-02b0-4670-b34d-cdc941a875a4.png)
![1629134421(1)](https://user-images.githubusercontent.com/40064027/129603848-9b98afb8-04f0-40af-bb0d-23d13b510107.png)

**Comment by a597873885** [comment]
@Nginx1 你好，你的接口域名是localhost，请确认一下是否在本地运行的。
参考这个文档，提供更详细的日志给我：https://www.webfunny.cn/faq.html?blogUrl=https%3A%2F%2Fwww.webfunny.cn%2Fblog%2Fpost%2Finfo%2F66
