### ISSUE TITLE
探针代码问题

### ISSUE THREAD

**Issue by lijiawei0602** [a597873885/webfunny_monitor#2]
timeRecordArray.splice(i, 1);

在recordHttpLog方法中，在对timeRecordArray循环的过程中，不可以使用splice进行删除，因为每次的删除没改变数组内容，导致Array[index]取到的内容不是依次的。

**Comment by a597873885** [comment]
@lijiawei0602  你好，我大概能够猜到你的疑问。  可能你误会了我的用意，在ajaxLoadStart的时候，我存下了一个对象，包含开始时间和event

**Comment by a597873885** [comment]
@lijiawei0602 你好，虽然原因可能不同，但是timeRecordArray里边的内容确实不应该被删除，这样会导致很多数据被遗漏掉，我已经对此做了调整。感谢你提出的意见
