### ISSUE TITLE
这个项目不能下载下来吗

### ISSUE THREAD

**Issue by zhonglijun** [a597873885/webfunny_monitor#20]
$ git clone https://github.com/a597873885/webfunny_monitor.git
Cloning into 'webfunny_monitor'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (18/18), done.
Receiving objects:  32% (326/1007), 2.96 MiB | 8.00 KiB/s

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by a597873885** [comment]
可以下载，你这个应该是网络问题，因为内容比较多，下载比较慢些，可以换个网络重试下

**Comment by zhonglijun** [comment]
我试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "a597873885"<notifications@github.com&gt;; 
发送时间: 2019年11月1日(星期五) 下午4:08
收件人: "a597873885/webfunny_monitor"<webfunny_monitor@noreply.github.com&gt;; 
抄送: "2950458637"<2950458637@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [a597873885/webfunny_monitor] 这个项目不能下载下来吗 (#20)




可以下载，你这个应该是网络问题，因为内容比较多，下载比较慢些，可以换个网络重试下

**Comment by a597873885** [comment]
@zhonglijun 如果还不行，就fork到你自己的仓库里下载，或者直接打包zip下载

**Comment by zhonglijun** [comment]
下载ZIP太慢了 几KB


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"a597873885"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 下午4:17
收件人:&nbsp;"a597873885/webfunny_monitor"<webfunny_monitor@noreply.github.com&gt;;
抄送:&nbsp;"2950458637"<2950458637@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [a597873885/webfunny_monitor] 这个项目不能下载下来吗 (#20)




@zhonglijun 如果还不行，就fork到你自己的仓库里下载，或者直接打包zip下载
