### ISSUE TITLE
埋点系统生成SDKJS存在问题,会导致埋点数据上传失败,不知道是否是配置存在问题

### ISSUE THREAD

**Issue by reed0214** [a597873885/webfunny_monitor#208]
生成的SDKJS中上传域名缺少http
![微信截图_20211124164408](https://user-images.githubusercontent.com/13160124/143204305-71024e1c-9b9c-43a8-9a53-72b490c21ec7.png)
头

**Comment by a597873885** [comment]
「上传域名缺少http」 这个配置是为了跟你项目的协议匹配。正常情况下是没问题的。  除非你是https协议，而你部署的服务不支持https协议就会上报失败

**Comment by a597873885** [comment]
@reed0214 那你把上报的接口的curl复制给我看下

**Comment by reed0214** [comment]
> @reed0214 那你把上报的接口的curl复制给我看下

我自己手动修改sdk代码加上http头是可以正常使用的，现在的问题是生成的sdk里面，关于上传接口的地址本身就是缺少http头的，您那边看图片应该能够看到吧，就是红框标注的，我这个是格式化之后的sdk代码，生成的时候就直接没有http头了

**Comment by a597873885** [comment]
//www.xxx.com/tracker/upevent   这种写法应该会自动带上协议头啊，你的不行？ @reed0214

**Comment by reed0214** [comment]
> //www.xxx.com/tracker/upevent 这种写法应该会自动带上协议头啊，你的不行？ @reed0214

没有，您看看我图片左边的domain里面，我直接都是默认的localhost，什么都没有改的

**Comment by a597873885** [comment]
@reed0214 你是用file的方式打开的，所以不行。 尝试放到正常的server里看下
