### ISSUE TITLE
埋点系统,同一网页调用多个探针SDK问题

### ISSUE THREAD

**Issue by reed0214** [a597873885/webfunny_monitor#209]
埋点系统,同一网页调用多个探针SDK会因为方法名相同出现先加入的js中无法正确找到自己的方法而报错
后添加的sousuo_main.js可以正常调用,但是biaoti_main.js会调用失败
![微信截图_20211124180611](https://user-images.githubusercontent.com/13160124/143217931-b16e171d-e814-43f7-a541-d5c5b3c9078c.png)
![微信截图_20211124180707](https://user-images.githubusercontent.com/13160124/143217938-50086146-3e8b-4690-844c-74b46a92e6cf.png)
![微信截图_20211124180810](https://user-images.githubusercontent.com/13160124/143218016-b163fe26-a4a0-47f0-80ad-04a958ea3ce4.png)

**Comment by a597873885** [comment]
@reed0214 你好，埋点的问题请到埋点系统的项目里提issues哈。  你为什么会引入两次sdk呢？

**Comment by reed0214** [comment]
> @reed0214 你好，埋点的问题请到埋点系统的项目里提issues哈。 你为什么会引入两次

不好意思提错位置了，不是引入两次，是引入两个不同的sdk，因为sdk的生成不是也是针对一个点位的么，但是如果一个界面需要对多个不同点位进行处理呢，请问下，这个是要如何操作呢

**Comment by a597873885** [comment]
@reed0214 一个项目只需要一个sdk，可以添加多个点位。 只需要引入一次sdk就可以了。 可以看下这个文档哈：https://www.webfunny.cn/desEvent.html?blogUrl=https%3A%2F%2Fwww.webfunny.cn%2Fblog%2Fpost%2Finfo%2F88

**Comment by reed0214** [comment]
> @reed0214 一个项目只需要一个sdk，可以添加多个点位。 只需要引入一次sdk就可以了。 可以看下这个文档哈：https://www.webfunny.cn/desEvent.html?blogUrl=https%3A%2F%2Fwww.webfunny.cn%2Fblog%2Fpost%2Finfo%2F88

嗯嗯好的，懂了，看来是真没必要添加多个sdk，谢谢了
