### ISSUE TITLE
上报请求ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by allenliu123** [a597873885/webfunny_monitor#211]
uplog 请求报错 ERR_CONNECTION_CLOSED
![](https://static.ifthat.com/public/data/7dd3488d39c272f9-image.png)
![](https://static.ifthat.com/public/data/42d44c5360e94c12-image.png)
我再本地环境是可以请求到的，生产环境请求不到
![](https://static.ifthat.com/public/data/77ed4b046710be62-image.png)

**Comment by Okswwen** [comment]
来信，文文已收到，我会尽快回复你的、感谢你的来信...

**Comment by a597873885** [comment]
@allenliu123 https的问题i，请看下这个文档 的第三条  https://webfunny.cn/faq.html?blogUrl=https%3A%2F%2Fwww.webfunny.cn%2Fblog%2Fpost%2Finfo%2F65

**Comment by allenliu123** [comment]
嗯嗯，已经解决了，感谢🙏
