### ISSUE TITLE
为什么本地启动监控系统，接口成功（数据库有数据），但接口返回都是空数组呢

### ISSUE THREAD

**Issue by ann7140** [a597873885/webfunny_monitor#23]

**Comment by a597873885** [comment]
发下接口url

**Comment by ann7140** [comment]
http://localhost:8011/server/getJavascriptErrorInfoListByDay?timeType=&webMonitorId=1574825272334

**Comment by a597873885** [comment]
有些接口数据是空数组很正常，很多分析数据都不是实时生成，为了节省数据库的开销。服务运行一段时间就好了。

**Comment by ann7140** [comment]
现在BehaviorInfo20191127和JavascriptErrorInfo20191127 表内有数据，需要运行多久监控系统可以看到数据呢

**Comment by a597873885** [comment]
一般一个小时会有分析数据， 有些数据是实时的，你应该有看到吧，还是所有数据都没有

**Comment by ann7140** [comment]
http://localhost:8010/访问，接口都没有数据呢

**Comment by a597873885** [comment]
你的问题很奇怪，我刚才自己试了，上传数据没问题，能截图首页给我看下吗？

**Comment by a597873885** [comment]
![image](https://user-images.githubusercontent.com/26519165/69784855-c77efc00-11f1-11ea-9385-9ca8e2c6f99d.png)
这是最初的样子

**Comment by ann7140** [comment]
![企业微信截图_1c1d38c5-059a-4946-9b97-2fc9b62a149f](https://user-images.githubusercontent.com/28838610/69785116-525ff680-11f2-11ea-9d3b-2714d6d9e36d.png)

**Comment by ann7140** [comment]
![企业微信截图_2843e91a-567a-468d-9829-d0459bb54aff](https://user-images.githubusercontent.com/28838610/69785225-89cea300-11f2-11ea-8f7f-3057dbcfe138.png)

**Comment by a597873885** [comment]
排查步骤：

**Comment by a597873885** [comment]
排查步骤：
1. 对比一下探针里的项目标识跟project表里的webmonitorId 的值是否一样。（ 在探针里搜索这段代码 sessionStorage.CUSTOMER_WEB_MONITOR_ID，后边就是webmonitorId的值）
2. 从customerPV表里查出几条记录，看看webmonitorId是否跟上边的webmonitorId是相同的

**Comment by ann7140** [comment]
好的，谢谢了
