### ISSUE TITLE
执行npm run table_config，提示Error: Cannot find module 'E:\webfunny_monitor\table_config.js'

### ISSUE THREAD

**Issue by factory011** [a597873885/webfunny_monitor#234]
接口提示日志表不存在，npm run table_config命令废弃后，怎么处理日志表未创建的问题？

**Comment by a597873885** [comment]
你好，表不存在，处理入口调整了，从 设置 -> 管理员特权 页面中，点击重建， 可以修复表问题  @factory011

**Comment by factory011** [comment]
好的，谢谢，建议同步更新下文档
![image](https://user-images.githubusercontent.com/40537912/173284523-ca642963-b702-4b15-957a-29f5fbced696.png)
