### ISSUE TITLE
用户邮箱注册失败

### ISSUE THREAD

**Issue by cnbizhh** [a597873885/webfunny_monitor#25]
一直报邮箱验证码有误, 请重新输入
![image](https://user-images.githubusercontent.com/7309951/69840907-2303c500-1298-11ea-8ec1-0d39111b5d7c.png)

**Comment by a597873885** [comment]
你的邮箱是以什么开头，我看看有没有验证码

**Comment by cnbizhh** [comment]
> 你的邮箱是以什么开头，我看看有没有验证码

![image](https://user-images.githubusercontent.com/7309951/69841962-53e5f900-129c-11ea-986c-9fb5a24d1728.png)

**Comment by a597873885** [comment]
我已经将这个验证码加入进来了，这是项目的一个bug，我会尽快修复。
