### ISSUE TITLE
无法创建新项目

### ISSUE THREAD

**Issue by gltzgl** [a597873885/webfunny_monitor#26]
点击创建没有反应，怎么破？
![微信截图_20191203154505](https://user-images.githubusercontent.com/45555181/70030301-e8759180-15e3-11ea-9d1f-77409511a4e5.png)

**Comment by a597873885** [comment]
mysql数据库配好了吗？

**Comment by a597873885** [comment]
根目录下logs目录下有错误日志，可以查看一下

**Comment by gltzgl** [comment]
数据库配置好了，没问题。就是点击创建没反应。错误日志没有消息

**Comment by a597873885** [comment]
我发布新版本，增加了后台日志的输出，你可以拉去最新代码，看看控制台输出日志如何？

更新方法： https://github.com/a597873885/webfunny_monitor/blob/master/Document.md#%E6%9B%B4%E6%96%B0%E4%BB%A3%E7%A0%81
