### ISSUE TITLE
创建新项目接口没有响应，后台也没记录日志，怎么回事？

### ISSUE THREAD

**Issue by andybbc** [a597873885/webfunny_monitor#28]
进入到创建新项目，生成探针代码步骤，填写信息点击创建按钮后，接口没有响应，后台webfunny_monitor/logs也没有看到错误日志，是哪里配置错了吗
http://localhost:8011/server/createNewProject

**Comment by a597873885** [comment]
可以把控制台信息和错误日志贴出来吗？

**Comment by andybbc** [comment]
[2019-12-06T11:59:25.959] [ERROR] errorLog - msg: 删除表操作报错
err name: ReferenceError
err message: Sequelize is not defined
err stack: ReferenceError: Sequelize is not defined
    at _0x4cf55c.(anonymous function)._0x4a8324 (/root/src/webfunny_monitor/controllers/controllers.js:1:121229)
    at Array.forEach (<anonymous>)
    at Timeout.setTimeout [as _onTimeout] (/root/src/webfunny_monitor/controllers/controllers.js:1:121216)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by andybbc** [comment]
Executing (default): SHOW INDEX FROM `CustomerPV20191207`
Executing (default): SHOW INDEX FROM `DailyActivity20191207`
Executing (default): SHOW INDEX FROM `EmailCode20191207`
Executing (default): SHOW INDEX FROM `ExtendBehaviorInfo20191207`
Executing (default): SHOW INDEX FROM `HttpErrorInfo20191207`
Executing (default): SHOW INDEX FROM `HttpLogInfo20191207`
Executing (default): SHOW INDEX FROM `JavascriptErrorInfo20191207`
Executing (default): SHOW INDEX FROM `LoadPageInfo20191207`
Executing (default): SHOW INDEX FROM `ResourceLoadInfo20191207`
Executing (default): SHOW INDEX FROM `ScreenShotInfo20191207`
Executing (default): SHOW INDEX FROM `VideosInfo20191207`
数据库表创建完成


[2019-12-06T11:00:05.595] [INFO] responseLog - msg: 

[2019-12-06T11:00:05.595] [INFO] responseLog - msg: 自动化脚本异常, 如果数据库表已经创建完成，可以忽略这个异常。 如果数据库表没有创建请手动执行 npm run table_config 创建数据库表

**Comment by andybbc** [comment]
error.log和info.log就这么多信息

**Comment by andybbc** [comment]
页面上有部分接口是调用你的服务器接口，有部分是调用本地自己的接口。并且调用本地的接口都是不通的，后端接口日志没有输出错误信息，该怎么解决？

**Comment by a597873885** [comment]
@andybbc  从你给出的日志我也看不出来什么问题，我的建议是重新按照部署步骤再执行一次吧。每一步都是必要的，不要漏掉。

**Comment by a597873885** [comment]
前端控制台，后台控制台， logs/error，结合这三个地方的日志去解决吧。

**Comment by andybbc** [comment]
可以新建项目了，但是把探针代码放到页面后，页面上报请求 server/upLog接口确是404，是什么情况，麻烦回答下谢谢

后端logs/error信息如下：
[2019-12-06T15:10:13.916] [ERROR] errorLog - msg: TypeError: Cannot read property 'replace' of undefined

后台控制台信息：
POST /server/upLog - 0ms

**Comment by a597873885** [comment]
库里有日志吗

**Comment by andybbc** [comment]
这3张表落数据了
`behaviorinfo20191206`
`customerpv20191206`
`loadpageinfo20191206`

还有，页面请求了两次上报接口，第一次http 404，第二次http 200 ，这跟上报的内容有关系吗，我看第一次内容比较多

**Comment by a597873885** [comment]
接口报404可能是众多日志中的一条信息有问题，导致这个接口返回错误结果，正常情况下不影响其他日志的上报。

**Comment by andybbc** [comment]
首页查询的时候接口server/getTodayFlowData报错，我看后端error日志信息如下：
err message: Table 'webfunny.customerpv20191205' doesn't exist

但是数据库只生成了`customerpv20191206`和`customerpv20191207`表，并没有customerpv20191205，请问怎么回事，谢谢

**Comment by a597873885** [comment]
![image](https://user-images.githubusercontent.com/26519165/70309685-02fc7480-1849-11ea-9ded-f64a55f670b8.png)

**Comment by a597873885** [comment]
5）项目成功运行后，有些接口报404属于正常现象，因为很多数据还未生成，一般运行7天以后，都会恢复正常。

**Comment by andybbc** [comment]
基本已经没大问题了，不过在接口请求错误统计server/getHttpErrorListByDay 接口报错了，信息如下：

err name: TypeError
err message: Cannot read property 'createdAt' of undefined
err stack: TypeError: Cannot read property 'createdAt' of undefined
    at HttpErrorInfoModel.(anonymous function)._0x373b6c (/root/src/webfunny_monitor/controllers/controllers.js:1:25336)

是少了字段吗

**Comment by andybbc** [comment]
能加个联系方式吗，后续如果有需求还得多请教您，您可以把微信号发我邮箱下1347387425@qq.com，谢谢了

**Comment by a597873885** [comment]
有问题的话就在git上给我留言吧，我们在这里解决，也许你遇到的问题，别人也会遇到
