### ISSUE TITLE
本地启动后登录还是一直重定向

### ISSUE THREAD

**Issue by funnyabc123** [a597873885/webfunny_monitor#296]
拉的是最新的代码05-22，下面两个地址登陆完后还是定向回登录页

**Comment by funnyabc123** [comment]
http://localhost:8008/webfunny_center/login.html?target=http%3A%2F%2Flocalhost%3A8014%2Fwebfunny_event%2FdataView.html

**Comment by funnyabc123** [comment]
http://localhost:8008/webfunny_center/login.html?target=http%3A%2F%2Flocalhost%3A8014%2Fwebfunny_event%2FdataView.html

**Comment by a597873885** [comment]
@funnyabc123 你好，我们排查了是因为数据库字段问题。你现在执行npm run restart 重启一下应该就可以了。 也可以添加我们的微信进行沟通

**Comment by funnyabc123** [comment]
@a597873885  可以了，感谢
