### ISSUE TITLE
关于pv、uv、ip数据统计问题

### ISSUE THREAD

**Issue by andybbc** [a597873885/webfunny_monitor#30]
请问下pv、uv数据统计是否准确，我看uv的数据明显不对，和pv很接近是怎么回事？

**Comment by a597873885** [comment]
能截图我看下吗？

**Comment by andybbc** [comment]
![image](https://user-images.githubusercontent.com/15723488/70507896-4831e680-1b68-11ea-8694-30ca60007602.png)

**Comment by a597873885** [comment]
这个数据说明用户只是进入应用，没有做太多的跳转操作，比如很多用户进来看一眼，就离开了，那么访问频次就会很低。

**Comment by a597873885** [comment]
访问频次越低，UV和PV的数据就会越接近

**Comment by a597873885** [comment]
因为这些数据看得是一个趋势，如果你们是在做测试，比如一个人没事在那里一直测试，那数据抽样出来的结果就不准了。 可以看下我网站上的L数据，人均访问频次是5.6，意思就是每人平均会访问5.6个页面，这符合我的预期。
