### ISSUE TITLE
部署过程中执行npm run table_config报错

### ISSUE THREAD

**Issue by Micheal-yang-china** [a597873885/webfunny_monitor#31]
> webfunny_monitor@1.0.0 table_config /root/webfunny_monitor-master
> node table_config.js 2 && npm run table_create

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'atob'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/webfunny_monitor-master/util/utils.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webfunny_monitor@1.0.0 table_config: `node table_config.js 2 && npm run table_create`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webfunny_monitor@1.0.0 table_config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-10T08_38_06_365Z-debug.log

**Comment by a597873885** [comment]
执行以下命令：npm install atob --save

**Comment by Micheal-yang-china** [comment]
执行完了之后报另一个错：
> webfunny_monitor@1.0.0 table_config /root/webfunny_monitor-master
> node table_config.js 2 && npm run table_create

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'nodemailer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/webfunny_monitor-master/util/utils.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webfunny_monitor@1.0.0 table_config: `node table_config.js 2 && npm run table_create`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webfunny_monitor@1.0.0 table_config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-10T08_55_56_874Z-debug.log

**Comment by a597873885** [comment]
😂按照教程来吧，你应该是跳过了某些步骤。   安装依赖包， 执行一下  npm install 就可以了

**Comment by Micheal-yang-china** [comment]
依赖包安装完成之后，执行npm run table_config还是报错：
> webfunny_monitor@1.0.0 table_config /root/webfunny_monitor-master
> node table_config.js 2 && npm run table_create


> webfunny_monitor@1.0.0 table_create /root/webfunny_monitor-master
> node table_create.js 20191210 && node table_create.js 20191211

/root/webfunny_monitor-master/table_create.js:12
    const BehaviorInfo = Sequelize.import('./schema_temp/behaviorInfo');
                                   ^

TypeError: Cannot read property 'import' of undefined
    at createTable (/root/webfunny_monitor-master/table_create.js:12:36)
    at Timeout._onTimeout (/root/webfunny_monitor-master/table_create.js:108:13)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webfunny_monitor@1.0.0 table_create: `node table_create.js 20191210 && node table_create.js 20191211                                         `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webfunny_monitor@1.0.0 table_create script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-11T00_51_57_370Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webfunny_monitor@1.0.0 table_config: `node table_config.js 2 && npm run table_create`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webfunny_monitor@1.0.0 table_config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-11T00_51_57_397Z-debug.log

**Comment by a597873885** [comment]
感觉像是数据库没有配置好，你数据库配了吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Micheal-yang-china <notifications@github.com&gt;
发送时间: 2019年12月11日 08:53
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 部署过程中执行npm run table_config报错 (#31)




依赖包安装完成之后，执行npm run table_config还是报错：
  
webfunny_monitor@1.0.0 table_config /root/webfunny_monitor-master
 node table_config.js 2 &amp;&amp; npm run table_create
   
webfunny_monitor@1.0.0 table_create /root/webfunny_monitor-master
 node table_create.js 20191210 &amp;&amp; node table_create.js 20191211
  
/root/webfunny_monitor-master/table_create.js:12
 const BehaviorInfo = Sequelize.import('./schema_temp/behaviorInfo');
 ^
 
TypeError: Cannot read property 'import' of undefined
 at createTable (/root/webfunny_monitor-master/table_create.js:12:36)
 at Timeout._onTimeout (/root/webfunny_monitor-master/table_create.js:108:13)
 at ontimeout (timers.js:427:11)
 at tryOnTimeout (timers.js:289:5)
 at listOnTimeout (timers.js:252:5)
 at Timer.processTimers (timers.js:212:10)
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! webfunny_monitor@1.0.0 table_create: node table_create.js 20191210 &amp;&amp; node table_create.js 20191211                                         
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the webfunny_monitor@1.0.0 table_create script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2019-12-11T00_51_57_370Z-debug.log
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! webfunny_monitor@1.0.0 table_config: node table_config.js 2 &amp;&amp; npm run table_create
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the webfunny_monitor@1.0.0 table_config script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2019-12-11T00_51_57_397Z-debug.log

**Comment by Micheal-yang-china** [comment]
数据库配置应该没有问题呀：
/**
 * 你可以在这个文件里配置你自己的数据库
 */
const Sequelize = require('sequelize');
const sequelize = new Sequelize('webfunny', 'root', 'root', {
  host: '192.168.46.135',
  dialect: 'mysql',
  dialectOptions: {
    charset: "utf8mb4",
    supportBigNumbers: true,
    bigNumberStrings: true
  },
  pool: {
    max: 50,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
  timezone: '+08:00' //东八时区
});

module.exports = {
  sequelize: sequelize
}

**Comment by a597873885** [comment]
@Micheal-yang-china 你能够通过Navicat 连接上你的mysql吗？

另外，我已经简化了部署步骤，你也许可以拉取最新代码尝试一下。

**Comment by Micheal-yang-china** [comment]
好的，我在试试
