### ISSUE TITLE
漏斗计算的结果问题

### ISSUE THREAD

**Issue by Synaric** [a597873885/webfunny_monitor#316]
我创建了一个漏斗，如下：
![image](https://github.com/a597873885/webfunny_monitor/assets/14257631/2a37d9fd-dafa-482b-b603-bbee3132bb66)
计算结果有误：
![image](https://github.com/a597873885/webfunny_monitor/assets/14257631/2498c26e-50b2-4801-8cbd-45864c33fc68)
可以看到步骤1是0人，实际情况是今天同一个用户先上报了打开APP，再上报首页点击TAB，应该是今天总数1人，100%转化才对。

数据库中，event106_13_20230808（首页点击TAB）数据如下：
![image](https://github.com/a597873885/webfunny_monitor/assets/14257631/cf178542-7273-4cba-960c-532191e5e66b)
event106_15_20230808（打开APP）数据如下：
![image](https://github.com/a597873885/webfunny_monitor/assets/14257631/a2ec5f27-3095-4543-a00b-1a8fef2072b8)
所有数据出自同一userId。
请问下，漏斗计算的依据是什么？

**Comment by a597873885** [comment]
你好，漏斗的数据计算需要先创建关系，然后开始计算漏斗数据。如果数据只有一个的话有可能是漏斗创建的时机，跟创建关系的时机有冲突导致的。可以加下我们的微信，我们来给你解答一下。 微号：webfunny2

**Comment by Synaric** [comment]
已解答，谢谢
