### ISSUE TITLE
数据库分表，写表问题

### ISSUE THREAD

**Issue by andybbc** [a597873885/webfunny_monitor#32]
当天的数据库表已经生成，但是程序是往昨天的表里面写数据，请问是什么情况呢

**Comment by a597873885** [comment]
你是使用哪种表创建方式

**Comment by a597873885** [comment]
【方法一, 适合前端小白】 这个表创建方式有些bug，我正在处理

**Comment by andybbc** [comment]
我就执行了create_table.sh

**Comment by andybbc** [comment]
表创建是没问题的，刚才的问题我重启node后好了，可以往当天表里面写数据了。 那意思就是每天都要重启下node吗？

**Comment by a597873885** [comment]
我刚排查了一下，确实代码没有向最新表里插入数据，等我稍后更新一下，不好意思。 更新后无需重启

**Comment by andybbc** [comment]
好的

**Comment by a597873885** [comment]
你好，关于数据库分表，写表问题，我已经修复了。 同时我也简化了部署步骤，请拉取最新代码重新进行部署吧。

**Comment by andybbc** [comment]
嗯，好的

**Comment by a597873885** [comment]
@andybbc 抱歉，刚才的版本有点小问题，已经修复了，你拉取新代码，重新运行就可以了。

**Comment by andybbc** [comment]
昨天已经拉取你最后修复的代码了，早上发现还是没有往最新表里写数据，怎么回事呢

**Comment by a597873885** [comment]
😂 这下有点尴尬了。昨天回答你之后，我跟你说又改了一次，你是拉去最后那一次更新吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 汪星星 <notifications@github.com&gt;
发送时间: 2019年12月12日 09:46
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 数据库分表，写表问题 (#32)

**Comment by andybbc** [comment]
对，我是在你第二次修复后拉取代码的

**Comment by andybbc** [comment]
![image](https://user-images.githubusercontent.com/15723488/70676083-fa32f500-1cc5-11ea-8c33-304419e6977c.png)

**Comment by andybbc** [comment]
我已经是最新代码了

**Comment by a597873885** [comment]
你部署的操作系统是什么？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 汪星星 <notifications@github.com&gt;
发送时间: 2019年12月12日 10:00
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 数据库分表，写表问题 (#32)




我已经是最新代码了

**Comment by andybbc** [comment]
centos 7

**Comment by a597873885** [comment]
你好，看下pm2的log日志  一般在 /root/.pm2/log  目录下
看日志里是否有这样一段日志，这个是用来切换数据库表的。

PM2      | Stopping app:www id:0
PM2      | App [www:0] exited with code [0] via signal [SIGINT]
PM2      | pid=42318 msg=process killed
PM2      | App [www:0] starting in -fork mode-
PM2      | App [www:0] online

**Comment by andybbc** [comment]
centos也是这个目录/root/.pm2/logs ， 有两个日志文件www-error.log  www-out.log，你说的日志是在www-out.log里面吗？

**Comment by a597873885** [comment]
对，你查找一下，是否有这样一段记录。

**Comment by andybbc** [comment]
没有搜到相关的关键字，这就尴尬了

**Comment by andybbc** [comment]
在www-error.log里面看到有报错信息，跟这个有关吗
![image](https://user-images.githubusercontent.com/15723488/70678518-47ff2b80-1ccd-11ea-9f8e-223022c28554.png)

**Comment by a597873885** [comment]
那能否手动执行restart.sh 脚本文件，看是否能正常执行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 汪星星 <notifications@github.com&gt;
发送时间: 2019年12月12日 10:49
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 数据库分表，写表问题 (#32)




没有搜到相关的关键字，这就尴尬了

**Comment by andybbc** [comment]
可以正常执行

**Comment by andybbc** [comment]
![image](https://user-images.githubusercontent.com/15723488/70678762-fc00b680-1ccd-11ea-8813-ec055a6b4cab.png)

**Comment by a597873885** [comment]
晕，确实是报错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 汪星星 <notifications@github.com&gt;
发送时间: 2019年12月12日 10:51
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 数据库分表，写表问题 (#32)




在www-error.log里面看到有报错信息，跟这个有关吗

**Comment by andybbc** [comment]
哪里

**Comment by a597873885** [comment]
这个问题让我有些困惑，我可能需要一些时间排查。

**Comment by a597873885** [comment]
你好，关于数据无法正确插入的问题，已经修复了。 需要拉取最新代码，重新运行即可。

以下日志代表数据库表切换成功。
1. pm2 的日志里会有以下字样：

0|www  | 当前时间：16:06:00
0|www  | 即将重启服务....
PM2      | Stopping app:www id:0
PM2      | App [www:0] exited with code [0] via signal [SIGINT]
PM2      | pid=22419 msg=process killed
PM2      | App [www:0] starting in -fork mode-
PM2      | App [www:0] online

2. logs/info/ 目录下日志里会有如下日志：
[2019-12-12T16:06:00.017] [INFO] responseLog - msg: 当前时间：16:06:00

[2019-12-12T16:06:00.021] [INFO] responseLog - msg: 即将重启服务....

**Comment by andybbc** [comment]
好的

**Comment by andybbc** [comment]
现在程序会自动生成未来几天的数据库表吗，还是要手动执行来生成？

**Comment by a597873885** [comment]
@andybbc 这个版本会在每天的凌晨0点重启服务， 在这时候会自动生成当天的数据库表，无须再手动处理了。

**Comment by andybbc** [comment]
好的

**Comment by andybbc** [comment]
今天早上一看，这个问题终于是好了。辛苦楼主了

**Comment by a597873885** [comment]
终于好了，很是欣慰，哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 汪星星 <notifications@github.com&gt;
发送时间: 2019年12月13日 09:44
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 数据库分表，写表问题 (#32)

**Comment by a597873885** [comment]
终于好了，很是欣慰，哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 汪星星 <notifications@github.com&gt;
发送时间: 2019年12月13日 09:44
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 数据库分表，写表问题 (#32)




今天早上一看，这个问题终于是好了。辛苦楼主了
