### ISSUE TITLE
页面错误统计问题

### ISSUE THREAD

**Issue by andybbc** [a597873885/webfunny_monitor#33]
问下页面错误统计菜单下的接口请求错误统计报错，几天了一直加载不出来

getHttpErrorListByDay 接口报错，error log如下：

![image](https://user-images.githubusercontent.com/15723488/70763775-421e4e80-1d90-11ea-86d3-9b19d16bc7d5.png)

**Comment by andybbc** [comment]
还有，静态资源错误统计数一直是0，我觉得应该是有数据的，不知道是统计问题还是怎么回事

![image](https://user-images.githubusercontent.com/15723488/70763875-9fb29b00-1d90-11ea-9932-0a6f0d90e535.png)

**Comment by a597873885** [comment]
现在，主要问题已经解决，你先让服务运行几天，因为解决bug一直在重启，所以分析服务可能还没有触发。
我正在尝试用github上的版本部署到我自己的生产环境上，到时候应该会遇到这些问题，我一并解决了。

**Comment by andybbc** [comment]
ok
