### ISSUE TITLE
本地启动自己的服务报Strorage超出浏览器限制

### ISSUE THREAD

**Issue by popeer** [a597873885/webfunny_monitor#34]
添加探针之后，启动本地程序，打开浏览器访问自己的页面，js报错如下
Failed to set the 'HTTP_LOG' property on 'Storage': Setting the value of 'HTTP_LOG' exceeded the quota\
英文错误原因是浏览器的Application->Storage超出默认的5M限制。
请问，加了探针，会大量插入storage导致的吗？
除了改本浏览器默认storage大小，有没有更好的办法解决？
连续报了78个这样的错误，页面很卡。

**Comment by a597873885** [comment]
1. 你是什么浏览器？
2. 你的http_log日志很大，还是很多，大概有多少条？
3. 正常情况下， http_log的日志都都会截掉，一般不会超过300长度，这种情况很少见，能否提供更详细的错误日志

**Comment by popeer** [comment]
![Uploading webfun1.jpg…]()
见截图里这个探针里的代码，加载了16M的数据。

**Comment by a597873885** [comment]
![image](https://user-images.githubusercontent.com/26519165/71402419-c95ca380-2667-11ea-9436-8b89e3d286e8.png)
加群聊吧

**Comment by popeer** [comment]
探针位置放错地方了，问题已解决。
