### ISSUE TITLE
本地新建项目 探针代码插入页面有报错

### ISSUE THREAD

**Issue by Mrwangfan** [a597873885/webfunny_monitor#35]
![1577166683(1)](https://user-images.githubusercontent.com/22339042/71396360-b2608600-2654-11ea-9d32-e11c310b51b2.jpg)
并且统计页面会出现NaN
![1577166822(1)](https://user-images.githubusercontent.com/22339042/71396384-d15f1800-2654-11ea-90bc-e49520b97892.png)
 实时分布看板也有NaN
![image](https://user-images.githubusercontent.com/22339042/71397785-77ad1c80-2659-11ea-9a34-715093f4bbdc.png)

**Comment by a597873885** [comment]
你好，关于upLog这个接口，后台错误日志有打印什么吗？ /logs/error 目录下

**Comment by Mrwangfan** [comment]
/logs/error/
![QQ截图20191224145326](https://user-images.githubusercontent.com/22339042/71398985-2d2d9f00-265d-11ea-883f-46b4f9a00333.png)
/logs/info/
![QQ截图20191224145420](https://user-images.githubusercontent.com/22339042/71399082-839add80-265d-11ea-99b4-4ac111558aca.png)

**Comment by a597873885** [comment]
@Mrwangfan  有两个问题可能需要你帮忙确认一下
1. 看下上传的日志是否有遗漏，报错是否对上传日志有影响。可以通过  用户分析->用户细查（无userId）-> 点击查看详情  可以看到完整的日志记录。
2. 通过排查，目前初步认为是日志上传后，处理返回结果时，可能当前浏览器对这种处理方式不是很友好，我准备调整一下

**Comment by a597873885** [comment]
因为探针里边封装了一个简陋ajax，只用于上传日志。 我对这个错误做了处理，你重新创建探针，看看如何。 告诉我是否还存在这个问题。

**Comment by Mrwangfan** [comment]
我新建探针重启项目还是有报错
![QQ截图20191224153344](https://user-images.githubusercontent.com/22339042/71400820-daef7c80-2662-11ea-993d-873534e276a6.png)

**Comment by a597873885** [comment]
![image](https://user-images.githubusercontent.com/26519165/71401349-8ea53c00-2664-11ea-9580-ef8a9bf1f0a6.png)
扫码加群吧
