### ISSUE TITLE
有几个问题反馈一下

### ISSUE THREAD

**Issue by syw-Mjollner** [a597873885/webfunny_monitor#39]
1.创建了项目后无法删除项目
2.创建项目时生成的探针代码后续再也没地方看了，如过当时没有保存就凉凉了
3.创建项目输入中文名的话，会没有任何反应和提示，全英文没有问题
4.探针代码内upLog接口相关代码截取了我当前域名作为上报地址，非常不科学，我的前端和上报服务器是不在一台服务器上的，不就凉凉了，也不利于前端本地测试，
5.按照文档全部配置完毕，启动正常，但是前端确实会报一堆错误，后台log内也会报一堆错误，比如Table 'webfunny.CustomerPV20191224' doesn't exist，明明数据库里只有webfunny.CustomerPV20191225

**Comment by a597873885** [comment]
感谢你的反馈。
你说的这些问题我都基本知晓。当初本来只开源了探针，后来应大家要求，我开放了中后台的代码，同时也带来了使用上的诸多不便，我正在更新。目前的版本不会影响正常使用。
第四点，上报服务器是在根目录下config.js进行配置的，并非是截取当前域名

**Comment by syw-Mjollner** [comment]
![QQ图片20191226143318](https://user-images.githubusercontent.com/38242211/71462008-e373be80-27ec-11ea-8d46-91e02c0baa44.png)
![BC3CC659-DB1B-4608-854D-7A51026DBB2C](https://user-images.githubusercontent.com/38242211/71462076-1ddd5b80-27ed-11ea-8919-497b6fa65227.png)
一个是我的配置，一个是探针里实际调用的地址

**Comment by a597873885** [comment]
共有两处配置
1. 配置文件配置是你启动服务的域名。
2.你创建项目时，配置的才是你探针的上报域名，这两个域名必须要对应上才行。
从报错情况来看，你生成探针的时候，填写的应该是localhost:8011
应该填写htbug.173uu.com:8011 才对。

**Comment by syw-Mjollner** [comment]
事实上我清楚的记得，我当时填写的是htbug.173uu.com:8011，并且我的探针代码内，既有htbug.173uu.com:8011，又有localhost:8011

**Comment by a597873885** [comment]
再尝试一下呢，看清楚说明，如果域名是localhost，上报域名自动设置为localhost



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: syw-Mjollner <notifications@github.com&gt;
发送时间: 2019年12月26日 14:46
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 有几个问题反馈一下 (#39)




事实上我清楚的记得，我当时填写的是htbug.173uu.com:8011，并且我的探针代码内，既有htbug.173uu.com:8011，又有localhost:8011
