### ISSUE TITLE
请问，这个js的探针如何集成和使用，有没有示例，多谢~

### ISSUE THREAD

**Issue by zsq1314** [a597873885/webfunny_monitor#4]
通过向html页面中插入一段简单的JS探针代码，实现无埋点监控前端页面的用户行为-----这个的具体使用和配置示例，多谢~

**Comment by a597873885** [comment]
@zsq1314 
页面的导航栏里边有个按钮 "一键部署"， 点击进去，创建新的应用后，就会生成对应的探针代码，按照说明，部署到项目里就可以了。

**Comment by a597873885** [comment]
部署只有简单三步， 点击部署教程按钮就可以看到，这个问题，我关闭了。
