### ISSUE TITLE
创建新项目接口报404 /server/createNewProject

### ISSUE THREAD

**Issue by songpeng0501** [a597873885/webfunny_monitor#41]
创建新项目接口报404 /server/createNewProject

**Comment by a597873885** [comment]
先在浏览器控制台执行一下  webfunny.wm_check()  看看配置信息如何？

**Comment by songpeng0501** [comment]
现在配置都成功了。但是监控拿不到上报的错误日志，访问量也取不到

**Comment by a597873885** [comment]
你光说这一句话，我是无法排查出问题的。你需要提供更多的信息给我。比如：
先在浏览器控制台执行一下 webfunny.wm_check() 看看配置信息如何？
再看看logs/error目录下的错误日志

**Comment by songpeng0501** [comment]
webfunny.wm_check()
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 ================================配置检查===============================
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 =【探针标识】：webfunny_1578550756418
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 =【上报接口】：http://localhost:8010/server/upLog
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 ......................................................................
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 = PVUV监控状态：启动...
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 = 静态资源监控状态：启动...
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 = JS错误监控状态：启动...
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 = 接口请求监控状态：启动...
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 = 静态资源监控状态：启动...
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 = 用户行为监控状态：启动...
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 = 用户信息初始化状态：用户信息初始化：userId=123456，版本号：1.0
iframeDemo.html?_ijt=ttmm38hmci4dmpqhm5km8ff75n:9 ======================================================================
"结束"

**Comment by songpeng0501** [comment]
method: GET
originalUrl:  /server/project/list?userEmail=362015972%40qq.com&webMonitorId=1573444026113
client ip:  ::1
query:  undefined
response time: 0
err name: SequelizeConnectionError
err message: Client does not support authentication protocol requested by server; consider upgrading MySQL client
这个是错误日志 麻烦帮忙看下

**Comment by a597873885** [comment]
【上报接口】：http://localhost:8010/server/upLog

上报接口应该配置为：http://localhost:8011/server/upLog

**Comment by songpeng0501** [comment]
兄弟方便加个qq 吗 362015972  好友密码 宋鹏

**Comment by a597873885** [comment]
【微信号】webfunny_2020  加这个微信号进群
