### ISSUE TITLE
创建项目报错

### ISSUE THREAD

**Issue by Micheal-yang-china** [a597873885/webfunny_monitor#42]
POST http://localhost:8011/server/createNewProject net::ERR_CONNECTION_REFUSED
Network request failed
网络开小差了，稍后再试吧 2

**Comment by a597873885** [comment]
@Micheal-yang-china logs/error 里边有日志吗？

**Comment by Micheal-yang-china** [comment]
没有，文件是空的
[root@localhost errors]# du -sh error-2020-01-09.log
0       error-2020-01-09.log

**Comment by a597873885** [comment]
其他接口都报错吗？ 还是只有这一个接口

**Comment by Micheal-yang-china** [comment]
我找到原因了，我在虚拟机上部署的，api地址填的localhost，改成ip就好了

**Comment by a597873885** [comment]
OK
