### ISSUE TITLE
部署后启动，卡在“首次访问较慢，请稍等几秒钟哦”

### ISSUE THREAD

**Issue by mynotezack** [a597873885/webfunny_monitor#44]
参照git上的部署文件启动程序，一直卡在“首次访问较慢，请稍等几秒钟哦”这里

查看了pm2的日志，服务启动正常
查看了logs里面的error和info日志，也没有任何有价值的信息

请问我该如何排查问题所在呢？

**Comment by a597873885** [comment]
这个应该浏览器控制台报错了，能看下吗？
