### ISSUE TITLE
录屏功能大概什么时间发布啊？

### ISSUE THREAD

**Issue by zycFran** [a597873885/webfunny_monitor#45]

**Comment by a597873885** [comment]
这个暂时我还不能确定，因为这个功能还需要一段时间开发。

**Comment by zycFran** [comment]
我看demo里的debug功能，好像录屏只是监测具体某个用户的所有行为。
想问下，录屏功能最后的实现会关联到具体的一个错误日志吗? 
这样的话在监测到错误时，直接查看录屏回放，看到错误的重现步骤就很完美了。

**Comment by a597873885** [comment]
@zycFran 你说的本来是我最初考虑的模式，但是我不确定未来会不会做成这个样子，目前我会优先把debug模式开发出来。
