### ISSUE TITLE
首页不能打开问题

### ISSUE THREAD

**Issue by kszit** [a597873885/webfunny_monitor#46]
2020-2-18 21:00 左右拉的代码，
本地部署，后台控制台没有报错。

浏览器控制台错误：
![image](https://user-images.githubusercontent.com/3717177/74739820-9b28c800-5294-11ea-928a-c9d4be160557.png)

**Comment by a597873885** [comment]
localhost:8010/home.html

**Comment by kszit** [comment]
感谢感谢，可以访问了。
