### ISSUE TITLE
创建项目，邮箱长度20限制太短了

### ISSUE THREAD

**Issue by Zhujinyong** [a597873885/webfunny_monitor#5]
![image](https://user-images.githubusercontent.com/19586695/61842596-576f0b00-aecb-11e9-8d39-5b854fbe0802.png)

**Comment by a597873885** [comment]
@Zhujinyong 邮箱限制已经调整了。

**Comment by DyncKathline** [comment]
@Zhujinyong 你那有webfunny_admin和webfunny_servers代码吗？
