### ISSUE TITLE
请问一下,部署了最新的代码后,项目启动后,打不开页面

### ISSUE THREAD

**Issue by hao-have-no** [a597873885/webfunny_monitor#50]
拉了最新代码,node8的环境下安装了相关的依赖包,改了本地的数据库配置,申请了临时许可证后.
 npm run local_start
启动项目,打不开页面,请问这是因为什么导致的

![error2](https://user-images.githubusercontent.com/22188003/75748171-be09b080-5d59-11ea-91ee-1627c26495e7.png)
![error-1](https://user-images.githubusercontent.com/22188003/75748177-bfd37400-5d59-11ea-81c7-7736dacc1024.png)

**Comment by a597873885** [comment]
http://localhost:8010/webfunny/overview.html

**Comment by hao-have-no** [comment]
感谢,解决了
