### ISSUE TITLE
请问如果不使用本地rabbitmq，使用其他机器上的rabbitmq，配置文件怎么配呢？教程里面只有开启和关闭rabbitmq功能的设置

### ISSUE THREAD

**Issue by ZhuYin1990** [a597873885/webfunny_monitor#55]

**Comment by a597873885** [comment]
@ZhuYin1990   暂时只支持本机上的消息队列。  

消息队列连接的配置文件在 lib/RabbitMq.js文件里，你可以自己去修改配置

**Comment by ZhuYin1990** [comment]
嗯嗯，之前没找到它，在本地装了个rabbitmq使用默认配置成功开启了消息队列功能。另外温馨提醒一下，有个错别字。消息队列的队字。右下角的“自我检查”按钮点开你就发现了。我是后端，已按贵教程成功搭建了服务，前端不是很懂，还需要学习如何将探针代码插到对应的应用中去。

**Comment by a597873885** [comment]
好的，感谢你的提醒
