### ISSUE TITLE
请问怎么配置数据库端口？

### ISSUE THREAD

**Issue by hahacium** [a597873885/webfunny_monitor#56]
在 db_local.js 的 defaultConfig 加上 port 后数据库还是没有写入表

**Comment by a597873885** [comment]
@hahacium mysql默认端口号是3306，正常情况下不用配置。
1. 确保你的用户名，密码都是正确的，可以先用Navicat连接你的mysql数据库试试。
2. 如果是阿里云服务器上的mysql，要确保安全组设置里有3306端口号

另外，如果有错误日志，请截图贴出来
