### ISSUE TITLE
7天里面pv统计有问题，数量不对，昨天下午看还好多，今天看少了好多，比如昨天下午统计量600，今天一看1百多，不知道怎么算的

### ISSUE THREAD

**Issue by liuyushihao123** [a597873885/webfunny_monitor#58]
这个7天里面统计量是否是算7天的和

**Comment by a597873885** [comment]
有截图吗？ 听你描述的信息，我可能无法为你解答

**Comment by a597873885** [comment]
@liuyushihao123  你点击7天后，uv的统计会显示在第一行，是不是看成pv了

**Comment by liuyushihao123** [comment]
> 有截图吗？ 听你描述的信息，我可能无法为你解答
![Uploading 20200515134654.jpg…]()
![Uploading 20200515134654.jpg…]()
![Uploading 20200515134654.jpg…]()

**Comment by liuyushihao123** [comment]
![20200515134654](https://user-images.githubusercontent.com/25860312/82016252-31616400-96b3-11ea-8421-ec9fc6840eb4.jpg)

**Comment by liuyushihao123** [comment]
![image](https://user-images.githubusercontent.com/25860312/82016453-ad5bac00-96b3-11ea-9e79-8ef8818f8412.png)

**Comment by a597873885** [comment]
@liuyushihao123  确实是计算有问题， 已修复更新。
