### ISSUE TITLE
前端工程中如何去进行埋点呢

### ISSUE THREAD

**Issue by victory460** [a597873885/webfunny_monitor#59]
您说的：通过向html页面中插入一段简单的JS探针代码，实现无埋点监控前端页面的用户行为。
前端工程中如何去进行埋点呢？有sdk？这个有没有个简单的例子参考下，非常感谢。

**Comment by a597873885** [comment]
你问的这个应该属于自定义埋点功能。
目前支持自定义日志，调用方法可以参考：http://www.webfunny.cn/website/api.html

关于自定义埋点的分析，这个功能会在后期的版本中发布。
