### ISSUE TITLE
报错：set the 'JS_ERROR'

### ISSUE THREAD

**Issue by MyButifullyLife** [a597873885/webfunny_monitor#60]
(index):2 Uncaught DOMException: Failed to set the 'JS_ERROR' property on 'Storage': Setting the value of 'JS_ERROR' exceeded the quota.

**Comment by yangyuan02** [comment]
我也遇到了这个问题，"JS_ERROR",偶发性的，会导致整个页面挂掉，页面点击任何位置都报错，无法操作了

**Comment by a597873885** [comment]
@MyButifullyLife @yangyuan02  两位用户， 此问题已修复，更新了探针代码。请更新使用吧。
