### ISSUE TITLE
k8s部署，怎么修改访问地址

### ISSUE THREAD

**Issue by liuxin638507** [a597873885/webfunny_monitor#61]
直接用localhost虽然能打开web界面，但是报错获取不到数据库的数据
module.exports = {
    localServerDomain: '//localhost:8011', // 日志服务域名  书写形式：//localhost:8011
    localAssetsDomain: '//localhost:8010', // 数据可视化服务域名 书写形式：//localhost:8010
    localServerPort: '8011',               // 日志服务端口号
    localAssetsPort: '8010',               // 可视化系统端口号

**Comment by a597873885** [comment]
1. 根目录下，进入 bin/domain.js  文件，修改访问地址以后，再生成镜像文件。

2. 获取不到数据库的数据，请问，是否尝试使用Navicat连接你的收据库？

**Comment by a597873885** [comment]
ip只能作为测试使用，而且ip不能够支持双协议。 生产环境最好使用域名，并且支持双协议



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liuxin638507 <notifications@github.com&gt;
发送时间: 2020年5月30日 00:11
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: a597873885 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] k8s部署，怎么修改访问地址 (#61)





 
k8s  pod容器ip是变化的，修改访问地址就不适用了，我想的话，怎么获取容器的ip？再启动服务

**Comment by liuxin638507** [comment]
请问下这个
ocalServerDomain: '//localhost:8011', // 日志服务域名 书写形式：//localhost:8011
localAssetsDomain: '//localhost:8010', // 数据可视化服务域名 书写形式：//localhost:8010
 localhost怎么以变量的形式传递给容器或者宿主机？

**Comment by a597873885** [comment]
代码在你手里，你可以自己尝试传递。
