### ISSUE TITLE
自定义埋点问题

### ISSUE THREAD

**Issue by yangzonglin3716** [a597873885/webfunny_monitor#68]
尝试使用了自定义埋点功能，会出现一下错误，请问是什么原因呢？
![微信截图_20200628181522](https://user-images.githubusercontent.com/55070193/85944701-6c6ddd00-b96b-11ea-9266-a1baa3284c60.png)
![微信截图_20200628181541](https://user-images.githubusercontent.com/55070193/85944707-75f74500-b96b-11ea-8831-0d269dcb1357.png)
前台代码中是这么写的
![1593339407(1)](https://user-images.githubusercontent.com/55070193/85944718-96270400-b96b-11ea-9f3a-9cc77b7e20b6.png)

我们前台使用的是vue

**Comment by a597873885** [comment]
你们前端ajax请求是否设置了 withCredentials 这个属性

**Comment by yangzonglin3716** [comment]
昨天我查看了下前端工程的配置确实开启了这个属性

**Comment by a597873885** [comment]
从错误提示来看，如果你设置了这个属性，那么监控系统的跨域配置就无法使用通配符(*)了，需指定允许跨域的域名，在根目录下找到app.js进行配置



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yangzonglin3716 <notifications@github.com&gt;
发送时间: 2020年6月29日 09:32
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: Webfunny 前端监控 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 自定义埋点问题 (#68)

**Comment by yangzonglin3716** [comment]
之前通配符的问题解决了，现在我定义的埋点并不能正常展示出数据这个是什么原因呢？我 针对于一个前台按钮的点击事件设置的埋点
![image](https://user-images.githubusercontent.com/55070193/87502122-5c583c00-c693-11ea-8497-7539e3dc759d.png)
![image](https://user-images.githubusercontent.com/55070193/87502171-7e51be80-c693-11ea-8eed-a0f23ad240e0.png)

**Comment by a597873885** [comment]
1. 确定一下是否上报了埋点，可以看下locationPoints 这个库里有没有数据
2. 埋点数据是每小时0分统计一次， 是否过了一小时了
