### ISSUE TITLE
没有捕获到js错误

### ISSUE THREAD

**Issue by MillionChen** [a597873885/webfunny_monitor#69]
这是本地起的项目截图

<img width="786" alt="WechatIMG218" src="https://user-images.githubusercontent.com/22833630/86030978-cf449e80-ba67-11ea-91f0-a7b586d94a0d.png">
<img width="1350" alt="WechatIMG219" src="https://user-images.githubusercontent.com/22833630/86030990-d370bc00-ba67-11ea-819c-3a2c721f8fa2.png">
<img width="1408" alt="WechatIMG220" src="https://user-images.githubusercontent.com/22833630/86031001-d8357000-ba67-11ea-9d08-c18084716f1a.png">
<img width="1119" alt="WechatIMG222" src="https://user-images.githubusercontent.com/22833630/86031009-d9ff3380-ba67-11ea-858d-5d81d32ed4d7.png">

**Comment by MillionChen** [comment]
附加控制台运行报错截图
![image](https://user-images.githubusercontent.com/22833630/86032365-d371bb80-ba69-11ea-9280-c65038179d81.png)

**Comment by a597873885** [comment]
@MillionChen  你好。
1. 第一张图确实属于js报错，正常来讲会入库的，能否确认一下数据库里是否有报错数据，如果有数据，应该会第一时间展现在页面下方的错误列表中
2. 部署项目传参 webfunny.wmInitUser("userId", "projectVersion")：  userId：代表你们项目用户的userId, 并非你们自己（你属于使用者）；projectVersion：代表你每次发布项目的版本号； 建议填写，也都可以不填写。 图中所指探针标识是自动写入到探针代码里的，无需关注。
3. 数据库是分表的，由于你运行的时间很短，往前的数据表还未生成，所以行为查询这个功能会抛出这些异常，不会影响影响使用，这个我后期会优化掉。

**Comment by qingbopro** [comment]
我也没有抓到js报错 react项目，是因为 window.localStorage.wmUserInfo = JSON.stringify({ userId: 'webfunny493', projectVersion: '1.0.1' }) 没有填写对吗？
