### ISSUE TITLE
git:webfunny_servers运行不起来，能更新一下吗

### ISSUE THREAD

**Issue by Zhujinyong** [a597873885/webfunny_monitor#7]

**Comment by a597873885** [comment]
@Zhujinyong 你好，如果你的问题解决了，可以把问题关掉了。

**Comment by Zhujinyong** [comment]
webfunny_servers需要做一些修改：
1、端口修改（bin/www）：
var port = normalizePort(process.env.PORT || '8010');

2、路由前缀修改（router/index.js）：
prefix: '/api/v1'

3、不使用本地数据库代码：
![image](https://user-images.githubusercontent.com/19586695/62178338-55012b00-b37b-11e9-91b5-237b72e35ee1.png)
