### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Winfury** [a597873885/webfunny_monitor#70]
0|webfunny |     code: 'ER_NOT_SUPPORTED_AUTH_MODE',
0|webfunny |     errno: 1251,
0|webfunny |     sqlState: '08004',
0|webfunny |     sqlMessage: 'Client does not support authentication protocol ' +
0|webfunny |       'requested by server; consider upgrading MySQL ' +
0|webfunny |       'client'

**Comment by a597873885** [comment]
看报错，好像mysql不知道用户名密码验证协议啊
