### ISSUE TITLE
启动后注册账号 提交报错

### ISSUE THREAD

**Issue by Winfury** [a597873885/webfunny_monitor#71]
[2020-07-01T09:48:23.814] [ERROR] errorLog - 
*************** error log start ***************
method: POST
originalUrl:  /server/registerCheck
client ip:  ::1
body: 
{"name":"admin","email":"937590662@qq.com","emailCode":"2445","password":"123456","type":"customer"}
response time: 0
err name: TypeError
err message: Cannot read property 'emailName' of null
err stack: TypeError: Cannot read property 'emailName' of null
    at registerCheck (C:\Users\93759\workspace\monitor\webfunny_monitor\controllers\controllers.js:1:146849)
    at async C:\Users\93759\workspace\monitor\webfunny_monitor\app.js:40:9
    at async C:\Users\93759\workspace\monitor\webfunny_monitor\middlreware\error.js:15:13
    at async C:\Users\93759\workspace\monitor\webfunny_monitor\app.js:22:9
*************** error log end ***************

**Comment by a597873885** [comment]
http://localhost:8010/webfunny/register.html?type=1    这里有点小问题， 你现在这里初始化一下管理员账号

**Comment by Winfury** [comment]
完美
