### ISSUE TITLE
docker启动的时候报错该./views/webfunny/w.js文件不存在，有人遇到 了嘛

### ISSUE THREAD

**Issue by yaowenbin** [a597873885/webfunny_monitor#72]
![image](https://user-images.githubusercontent.com/20135897/86206159-4419f480-bb9e-11ea-9385-2f88b4a3ef0f.png)

**Comment by a597873885** [comment]
npm run prd 命令执行完成后，会在webfunny下生成这个文件

**Comment by a597873885** [comment]
@yaowenbin 我把文档修正一下

**Comment by yaowenbin** [comment]
![image](https://user-images.githubusercontent.com/20135897/86510454-42f8f980-be22-11ea-95d3-4307587f4dac.png)
运行npm run prd报错

**Comment by a597873885** [comment]
@yaowenbin  你好，此bug已修复，请更新最新代码，运行即可。

**Comment by a597873885** [comment]
你好，此问题已修复，请更新代码，重新运行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yao <notifications@github.com&gt;
发送时间: 2020年7月4日 18:15
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: Webfunny 前端监控 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] docker启动的时候报错该./views/webfunny/w.js文件不存在，有人遇到 了嘛 (#72)





 

 运行npm run prd报错
