### ISSUE TITLE
第二天查看有关前一天JS报错统计丢失

### ISSUE THREAD

**Issue by unknownroad** [a597873885/webfunny_monitor#73]
第二天返回去看前一天的js报错，记录都没有了。请问一下大佬这是什么问题。
（不知道为啥现在上传不了图片）

**Comment by a597873885** [comment]
请问前一天的数据库表是否存在，控制台和logs/error 下是否有错误日志。

**Comment by unknownroad** [comment]
数据库表存在，控制台没有报错，只有一个warning

**Comment by a597873885** [comment]
那你把错误统计页面截图发我一下，如果上传不了图片，使用4G网络试试，或者加我的微信，我帮你解决
