### ISSUE TITLE
js的sdk文档在哪里。。。

### ISSUE THREAD

**Issue by qingbopro** [a597873885/webfunny_monitor#75]
js的sdk文档在哪里。。。

**Comment by a597873885** [comment]
创建项目的时候会有



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: daboge <notifications@github.com&gt;
发送时间: 2020年8月8日 11:20
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] js的sdk文档在哪里。。。 (#75)
