### ISSUE TITLE
动态删除监控代码的script标签，如何停止继续监控行为？

### ISSUE THREAD

**Issue by SubinY** [a597873885/webfunny_monitor#76]
微前端架构想通过监控某个模块的代码，通过路由监听动态增删scipt标签去解除监控，发现在第一次加载script后，部分全局事件被拦截监听。有没办法在不刷新页面的情况下彻底删除监控行为

**Comment by a597873885** [comment]
@SubinY  你好，webfunny目前只提供了停止上报日志的方法，不刷新页面，暂时无法彻底删除监控行为。

**Comment by SubinY** [comment]
> @SubinY 你好，webfunny目前只提供了停止上报日志的方法，不刷新页面，暂时无法彻底删除监控行为。

感谢作者回答，请问是如何停止上报呢？我看文档好像没说这一点

**Comment by a597873885** [comment]
在项目详情下边有



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mr.Hu <notifications@github.com&gt;
发送时间: 2020年8月13日 20:31
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: Webfunny 前端监控 <597873885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 动态删除监控代码的script标签，如何停止继续监控行为？ (#76)





  
@SubinY 你好，webfunny目前只提供了停止上报日志的方法，不刷新页面，暂时无法彻底删除监控行为。
  
感谢作者回答，请问是如何停止上报呢？我看文档好像没说这一点
