### ISSUE TITLE
接口的数据是空

### ISSUE THREAD

**Issue by npmrun** [a597873885/webfunny_monitor#78]
你好，怎么才能显示接口的数据呢，我的一直是空的，不管是数据量大的还是小的
![image](https://user-images.githubusercontent.com/62639956/90621258-0e13fb00-e246-11ea-81f3-8c49e696dae8.png)

**Comment by a597873885** [comment]
@npmrun  这是个bug，一直没时间修复，等我修复下，等下个版本更新下。

**Comment by npmrun** [comment]
好的
