### ISSUE TITLE
有个问题，我按照部署步骤部署后，我去哪里看监控的信息呢？还有可不可以支持下typescript。。

### ISSUE THREAD

**Issue by XSmarter** [a597873885/webfunny_monitor#8]

**Comment by a597873885** [comment]
@XSmarter 你好，每个页面上都有搜索框，可以在那里搜索你创建应用的名字，并点击选择即可。

**Comment by XSmarter** [comment]
个人感觉最好可以自己部署一套http://www.webfunny.cn 这个页面，不然需要依赖官网查看这个感觉太束缚了 。

**Comment by XSmarter** [comment]
还有比如，我不想让别人看到自己项目的相关数据，目前应该没法做到，所以期待开放出监控系统项目代码，可以自己进行布局搭建 
![image](https://user-images.githubusercontent.com/33716687/62749122-d51b4500-ba8d-11e9-8006-094169ec7b8f.png)

**Comment by a597873885** [comment]
@XSmarter 你好

关于没有开源中后台代码的声明
  非常感谢大家一直以来的关注，每次收到大家的star，都会非常激动，这也是我不断前进的动力，thank you very much!
如题，我没有开源中后台的原因有两点：

1. 我写这个的目的就是想让前端工程师能够拥有一个私人定制的前端监控系统，第一版我开源了中后台，收到了一些小伙伴的反馈："我的项目跑不起来"， "mysql数据库安装不上"，"数据库没有访问权限"等等。这并不是我想要看到的，如果你想随身拥有一个前端监控，需要拥有能够独立搭建中后台的能力。这样你想监控什么都没问题了。
2. 中后台经历过很多次迭代之后，有了很多的变化，包括中后台服务拆分，消息队列，多台服务器部署（我在博客里讲了）。我一个人的精力有限，运维能力很不专业，所以一切都显得很杂乱，所以我没有开源中后台的代码，在此表示歉意。
在未来，如果能够将这些服务整合，我会再发布出来。

关于中后台服务的建议
1. 如果你的应用流量不大，你可以直接使用网站上的部署功能，未来我会上线用户系统功能，将不同用户隔离开。
2. 你可以抽取探针中的某一个监控功能，先把你的中后台服务搭建起来，你会发现，非常简单。
