### ISSUE TITLE
linux服务器怎么部署这个项目

### ISSUE THREAD

**Issue by songlibin** [a597873885/webfunny_monitor#81]
1、项目使用npm run build打包嘛？或者其他的方式打包？
2、打包的项目怎么部署到linux服务器，可以麻烦指导下嘛？
3、你之前写的那个部署到服务器的方法，我不太理解，麻烦能不能详细说明下，怎么打包，怎么去部署到linux服务器上，感谢。

**Comment by a597873885** [comment]
你好，我现在在路上，稍后给你解答



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: songlibin <notifications@github.com&gt;
发送时间: 2020年8月26日 10:01
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] linux服务器怎么部署这个项目 (#81)





 
1、项目使用npm run build打包嘛？或者其他的方式打包？
 2、打包的项目怎么部署到linux服务器，可以麻烦指导下嘛？
 3、你之前写的那个部署到服务器的方法，我不太理解，麻烦能不能详细说明下，怎么打包，怎么去部署到linux服务器上，感谢。

**Comment by songlibin** [comment]
好的，感谢

**Comment by a597873885** [comment]
@songlibin 你好，方便加我微信吗？微信上给你解决方便些， webfunny_2020
