### ISSUE TITLE
日志上报调整频率页面报错

### ISSUE THREAD

**Issue by Okswwen** [a597873885/webfunny_monitor#82]
调整上报频率-->日志上报频率,确认更改时，页面报错。

报错信息：
http://localhost:8011/server/changeWaitCounts1 404 (Not Found)
setting.87e671798d0a0a39109c.min.js:1 更改状态失败

**Comment by a597873885** [comment]
@Okswwen 此接口确实报错了，我现在修复，更下个版本上线。 感谢提醒。

**Comment by Okswwen** [comment]
> @Okswwen 此接口确实报错了，我现在修复，更下个版本上线。 感谢提醒。

好，还有个问题。本地第一次跑npm run prd ,没有问题，手动关闭后，再次跑npm run prd 就会报下面的错误

[PM2][ERROR] Script already launched, add -f option to force re-execution

谢谢

**Comment by a597873885** [comment]
@Okswwen 重启请执行  npm run restart     或者执行命令：  pm2 stop webfunny | pm2 delete webfunny | npm run prd  

需要杀掉之前的进程。

**Comment by Okswwen** [comment]
恩，我尝试npm run restart，命令好使，表示感谢。
