### ISSUE TITLE
健康状态的分数值，显示异常

### ISSUE THREAD

**Issue by Okswwen** [a597873885/webfunny_monitor#83]
今日健康概况：
分数计算出现小数时，会显示不正确。
![15986026452696](https://user-images.githubusercontent.com/17465417/91538183-03461e00-e94a-11ea-81bc-88efdfbd0f79.png)

**Comment by a597873885** [comment]
确实是计算精度问题，我稍后修复下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: swwen <notifications@github.com&gt;
发送时间: 2020年8月28日 16:19
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 健康状态的分数值，显示异常 (#83)

**Comment by Okswwen** [comment]
感谢

**Comment by a597873885** [comment]
@Okswwen 你好，请问你的webfunny版本号是多少？

**Comment by Okswwen** [comment]
1.7.8
