### ISSUE TITLE
部署成功成功没办法,初始化管理员账号失败

### ISSUE THREAD

**Issue by hhcol620** [a597873885/webfunny_monitor#84]
![image](https://user-images.githubusercontent.com/56748103/91682593-a5514a80-eb84-11ea-95ac-602661111375.png)
服务端里面logs文件夹里面的日志都是空的,数据库navicat也能连接上,就是报这个错误

**Comment by hhcol620** [comment]
![image](https://user-images.githubusercontent.com/56748103/91682982-d54d1d80-eb85-11ea-8d30-11627f19041a.png)
还有这个报错

**Comment by a597873885** [comment]
如果没有日志，确实很难排查，你确定教程的每个步骤都执行了吗？我现在外出，不方便为你解答，可以加我微信，我到家后为你解答



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hhcol620 <notifications@github.com&gt;
发送时间: 2020年8月31日 12:25
收件人: a597873885/webfunny_monitor <webfunny_monitor@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[a597873885/webfunny_monitor] 部署成功成功没办法,初始化管理员账号失败 (#84)





 

 服务端里面logs文件夹里面的日志都是空的,数据库navicat也能连接上,就是报这个错误
