### ISSUE TITLE
查看足迹，报错500

### ISSUE THREAD

**Issue by Okswwen** [a597873885/webfunny_monitor#85]
Api接口统计页面，点击接口失败列表，，点击查看足迹，
接口：`server/searchCustomerBehaviors`，`server/searchCustomerInfo` 报错500

logs中的日志文件：

![1598856733842](https://user-images.githubusercontent.com/17465417/91691216-db4cf980-eb99-11ea-9da7-410b05d68536.png)
![1598856824701](https://user-images.githubusercontent.com/17465417/91691219-dc7e2680-eb99-11ea-8b51-43d29999f30a.png)

不知道是不是那个Na-Na的问题，谢谢。

**Comment by a597873885** [comment]
@Okswwen   你好，你加的微信吧，沟通方便一些  webfunny_2020
