### ISSUE TITLE
sourceMap源码解析问题

### ISSUE THREAD

**Issue by Okswwen** [a597873885/webfunny_monitor#86]
源码解析中，上传接口`server/uploadMapFile`没问题，可以正常上传，但是

返回的这个接口信息报500，`server/getJavascriptErrorStackCodeForSource`，

logs日志：

![15988583162449](https://user-images.githubusercontent.com/17465417/91693234-4ba94a00-eb9d-11ea-858b-ed06e8c12fee.png)

给点处理意见，谢谢

备注错误信息提示：
UncaughtInPromiseError: Cannot read property 'code' of undefined

at https://xxxxx/js/app.d8cfe6b5.js:2:3616

将此文件文件上传时候，就出现上面的那个问题，e6b5.js文件末尾为：‘ //# sourceMappingURL=app.d8cfe6b5.js.map’

**Comment by a597873885** [comment]
请加我微信，这个解析的情况比较复杂。 稍后我会补全文档。
